apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-sql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-sql
  template:
    metadata:
      labels:
        app: ms-sql
    spec:
      containers:
        - name: ms-sql
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Express"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-sql-secrets
                  key: SA_PASSWORD
          volumeMounts:
            - name: ms-sqldb
              mountPath: /var/opt/mssql/data
      volumes:
        - name: ms-sqldb
          persistentVolumeClaim:
            claimName: ms-sql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ms-sql-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: ms-sql
  ports:
    - name: ms-sql
      protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: ms-sql-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: ms-sql
  ports:
    - name: ms-sql
      protocol: TCP
      port: 1433
      targetPort: 1433