apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      containers:
        - name: rabbit-mq
          image: rabbitmq:3-management
          ports:
            - name: rmq-mgmt-port 
              containerPort: 15672
            - name: rmq-msg-port
              containerPort: 5672
---
apiVersion: v1
kind: Service
metadata: 
  name: rabbit-mq-cluster-ip-srv
spec:
  type: ClusterIP
  selector:
    app: rabbit-mq
  ports:
    - name: rmq-mgmt-cl-port
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rmq-msg-cl-port
      protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: rabbit-mq
  ports:
    - name: rmq-mgmt-lb-port
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: rmq-msg-lb-port
      protocol: TCP
      port: 5672
      targetPort: 5672
