apiVersion: v1
kind: Service
metadata:
  name: ticket-api-node-port-srv
spec:
  type: NodePort
  selector:
    app: ticket-api
  ports:
    - name: ticket-api-http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
